### ISSUE TITLE
Icone in Numeri del podcast

### ISSUE THREAD

**Issue by valeriogalano** [valeriogalano/pensieriincodice-website#4]
Nella sezione _Numeri del podcast_ mancano le icone:

![image](https://github.com/valeriogalano/pensieriincodice-website/assets/342634/db5f7384-9209-420c-a535-7cdb37549db2)

**Comment by progressify** [comment]
hai aggiunto una versione di ionicon troppo recente nel file `scripts.html`

```
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
```

 il template utilizza una versione mooolto vecchia, credo la v2
 hai due strade:
- utilizzi le icone vecchie con la vecchia sintassi (dovrebbe essere tutto qui https://nbs-it.github.io/ionicons-v2.0.1/#cdn)
- ti aggiorno il pacchetto icone

dimmi come vuoi che proceda

**Comment by progressify** [comment]
ho provato a sostituire brutalmente la nuova sintassi di ionicons nell'html e questo è il risultato infatti:

![image](https://github.com/valeriogalano/pensieriincodice-website/assets/11472632/3723d3a3-915e-4250-bc05-4a4fd8d7ef7c)

**Comment by progressify** [comment]
aggiorno le icone a ionicons 7

**Comment by progressify** [comment]
![image](https://github.com/valeriogalano/pensieriincodice-website/assets/11472632/a2c89e0a-66af-4612-b50b-6ad49b317860)

che ne pensi?
qui trovi la lista completa delle icone: https://ionic.io/ionicons

queste sono quelle che ho usato:
```
### Facts [ facts ]
facts:
  title: "Numeri del podcast"
  items:
    - icon: "mic"
      name: "120+ Episodi"

    - icon: "time"
      name: "40+ Ore di contenuti"

    - icon: "stats-chart"
      name: "200k+ Download"

    - icon: "calendar"
      name: "Online dal 2019"
```

dimmi se è tutto ok o se vuoi che usi qualche variante
